name: sentry_link
description: Automatic capture of exceptions and GraphQL errors for the gql eco-system, like graphql and ferry
version: 0.2.0
repository: https://github.com/ueman/sentry-dart-tools
issue_tracker: https://github.com/ueman/sentry-dart-tools/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  gql_error_link: ^0.2.0
  gql_exec: ^0.4.0
  gql_link: ^0.5.0
  gql: ^0.14.0
  sentry: ^7.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  graphql: ^5.1.3
